addConteudo/urls.py
from django.urls import include, path
from django.conf import settings
from django.urls import re_path
from django.views.static import serve
from . import views


app_name = 'add'
urlpatterns = [
    #path('',  views.Inicio.as_view(), name='usuario'),
    path('listar/',  views.postList.as_view(), name='listar'),
    path('listar/api/',   views.listarAPI.as_view(), name='listar-api'),
    path('manga/',  views.postManga.as_view(), name='manga'),
    path('manga/delete/<int:pk>/', views.mangaDelete.as_view(), name='mangaDelete'),
    path('manga/delete/<int:pk>/<int:cp>/',
         views.capDelete.as_view(), name='capDelete'),
    path('manga/<int:pk>/', views.mangaInfo.as_view(), name='mangaInfo'),
    path('manga/<int:pk>/api/', views.mangaInfoAPI.as_view(), name='mangaInfo-api'),
    path('manga/<int:pk>/addCap/', views.addCap.as_view(), name='addCap'),
    path('manga/<int:pk>/<int:cp>/', views.verCap.as_view(), name='capituloInfo'),
    path('manga/<int:pk>/<int:cp>/api/', views.CapituloInfoAPI.as_view(), name='capituloInfo-API'),
    path('manga/<int:pk>/<int:cp>/edt/', views.edtCap.as_view(), name='capitulo-edt'),
    path('manga/<int:pk>/<int:cp>/<int:pg>/', views.verPg.as_view(), name='pgManga'),
    path('manga/<int:pk>/<int:cp>/<int:pg>/api/', views.pgAPI.as_view(), name='pgManga-API'),
    #     name='editar-veiculo'),
    #path('novo/',   views.UsuarioNew.as_view(), name='cadastro'),
    #path('entrar/',   views.LoginView.as_view(), name='entrar'),
    #path('sair/',   views.sair, name='sair'),
    #path('editar/<int:pk>/', views.VeiculosEdit.as_view(),
    #     name='editar-veiculo'),
    #path('excluir/<int:pk>/',  views.VeiculosDelete.as_view(),
    #     name='deletar-veiculo'),
]

projetoFinal/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from addConteudo.views import lista

urlpatterns = [
    path('', lista.as_view(), name='inicio'),
    path('usuario/', include('usuario.urls', namespace="usuario")),
    path('add/', include('addConteudo.urls', namespace="add")),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuario/urls.py
from django.urls import include, path
from django.conf import settings
from django.urls import re_path
from django.views.static import serve
from . import views
from rest_framework.authtoken import views as rest_framework_views


app_name = 'usuario'
urlpatterns = [
    path('novo/',   views.UsuarioNew.as_view(), name='cadastro'),
    path('novo/api/',   views.UsuarioNewAPI.as_view(), name='cadastro-api'),
    path('entrar/',   views.LoginView.as_view(), name='entrar'),
    path('entrar/api/',   views.entrarAPI.as_view(), name='entrar-api'),
    path('<int:pk>/', views.infoPerfil.as_view(), name='perfil'),
    path('<int:pk>/api', views.infoPerfil.as_view(), name='perfil-api'),
    path('<int:pk>/editar/',   views.editarPerfil.as_view(), name='editar-perfil'),
    path('api/',   views.teste.as_view(), name='api2'),
    path('api/<int:pk>/',   views.teste.as_view(), name='api'),
    path('sair/',   views.sair, name='sair'),
    
    #path('editar/<int:pk>/', views.VeiculosEdit.as_view(),
    #     name='editar-veiculo'),
    #path('excluir/<int:pk>/',  views.VeiculosDelete.as_view(),
    #     name='deletar-veiculo'),
]

usuario/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse
from django.conf import settings
from rest_framework.authtoken.models import Token


@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.created(user=instance)

def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'user_{0}/capa/{1}'.format(instance.user.id, filename)

class Perfil(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    capa = models.ImageField(upload_to=user_directory_path, blank=True)
    dn = models.DateField(null=True, blank=True)
    sobre = models.TextField(blank=True)
    cidade = models.CharField(max_length=250, blank=True)
    def get_absolute_url(self):
        return reverse('perfil', kwargs={'pk': self.pk})



@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        perfil = Perfil(user=instance)
        perfil.capa = 'profile_image/defaut.jpeg'
        perfil.save()

usuario/forms.py
# -*- coding: utf-8 -*-
from django.forms import ModelForm, Textarea, ImageField
from django import forms
from django.contrib.auth.models import User 
from django.forms.utils import ErrorList
from .models import Perfil
from io import StringIO
from PIL import Image
from betterforms.multiform import MultiModelForm

class FormularioUsuario(forms.ModelForm):
    User._meta.get_field('email').blank = False
    User._meta.get_field('first_name').blank = False
    password_confirm = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'maxlength': 255}))
    
    class Meta:
        model = User
        fields = ['password', 'username',
                 'first_name', 'last_name', 'email']

        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'maxlength': 255}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'maxlength': 255}),
            'email': forms.TextInput(attrs={'class': 'form-control', 'maxlength': 255}),
            'password': forms.PasswordInput(attrs={'class': 'form-control', 'maxlength': 255}),
            'username': forms.TextInput(attrs={'class': 'form-control', 'maxlength': 255}),
        }

        error_messages = {
            'first_name': {
                'required': 'Campo Obrigatorio1'
            },
            'last_name': {
                'required': 'Campo Obrigatorio2'
            },
            'email': {
                'required': 'Campo Obrigatorio'
            },
            'username': {
                'required': 'Campo Obrigatorio'
            },
            'password': {
                'required': 'Campo Obrigatorio'
            },
        }

    def save(self, commit=True):
        
        user = super(FormularioUsuario, self).save(commit=False) 
        user.set_password(self.cleaned_data['password'])
        
        if commit:
            user.save() 
        return user



class LoginUsuario(forms.ModelForm):
    
    class Meta:
        model = User
        fields = ['password', 'username']

        widgets = {
            'password': forms.PasswordInput(attrs={'class': 'form-control', 'maxlength': 255}),
            'username': forms.TextInput(attrs={'class': 'form-control', 'maxlength': 255}),
        }
        error_messages = {
            'username': {
                'required': 'Campo Obrigatorio'
            },
            'password': {
                'required': 'Campo Obrigatorio'
            },
        }

class EditUser(forms.ModelForm):
    class Meta:
        model = User
        fields = ['id', 'first_name', 'last_name', 'email']

        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'maxlength': 255}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'maxlength': 255}),
            'email': forms.TextInput(attrs={'class': 'form-control', 'maxlength': 255}),
        }

class Imagem(forms.widgets.Widget):
    def render(self, name, value, attrs=None):
        html =  Template("""<img src="$link"/>""")
        return mark_safe(html.substitute(link=value))


class edtPerfil(forms.ModelForm):
    class Meta:
        model = Perfil
        fields = [
            'dn', 'cidade', 'sobre', 'capa'
        ]

        widgets = {
            'dn': forms.DateInput(format='%d/%m/%Y', attrs={'class': 'form-control', 'maxlength': 255}),
            'cidade': forms.TextInput(attrs={'class': 'form-control', 'maxlength': 255}),
            'sobre': forms.Textarea(attrs={'class': 'form-control', 'rows': 3 }),
            'capa': forms.FileInput(attrs={'class': 'form-control', 'id': 'capa_id', 'onchange': 'loadFile(event)'}),
        }

class perfilM(MultiModelForm):
    form_classes = {
        'user': EditUser,
        'perfil': edtPerfil,
    }

usuario/views.py
#-*- coding: utf-8 -*-
#https://krzysztofzuraw.com/blog/2016/two-forms-one-view-django.html
from .models import Perfil
from addConteudo.models import Manga
from usuario.forms import FormularioUsuario, LoginUsuario, perfilM

from django.http import HttpResponseRedirect
from django.views.generic import CreateView, FormView, UpdateView
from django.views.generic.detail import DetailView
from django.urls import reverse_lazy, reverse
from django.contrib.auth.models import User
from django.shortcuts import redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from rest_framework import viewsets
from .serialize import SnippetSerializer, CadastroSerializer, PerfilSerializer
from rest_framework import status, serializers
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework.views import APIView
from django.http import Http404
from django.contrib.auth import get_user_model
from rest_framework.authtoken.views import ObtainAuthToken
from rest_framework.authtoken.models import Token
from rest_framework.response import Response
from rest_framework.authentication import SessionAuthentication, BasicAuthentication
from rest_framework.permissions import IsAuthenticated


User = get_user_model()


class perfilAPI(APIView):
   
    def get(self, request, pk, format=None):
        snippet = self.get_object(pk)
        serializer = SnippetSerializer(snippet)
        return Response(serializer.data)

class teste(APIView):
    serializer_class = PerfilSerializer
    authentication_classes = (SessionAuthentication, BasicAuthentication)
    permission_classes = (IsAuthenticated,)

    def get_object(self, pk):
        try:
            return Perfil.objects.get(user=pk)
        except User.DoesNotExist:
            raise Http404
    
    def get(self, request, pk, format=None):
        snippet = self.get_object(pk)
        serializer = PerfilSerializer(snippet)
        return Response(serializer.data)

class entrarAPI(ObtainAuthToken):
    serializer_class = SnippetSerializer

    def post(self, request, *args, **kwargs): 
        username = self.request.POST.get('username', '')
        password = self.request.POST.get('password', '')            
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                token, created = Token.objects.get_or_create(user=user)      
                return Response({
                    'token': token.key,
                    'user_id': user.pk,
                    'nome': user.username
                })
            else:
                return Response({
                    'erro': 1
                })
        else:
            return Response({
                    'erro': 2
                })



class UsuarioNew(CreateView):

    model = User
    form_class = FormularioUsuario
    template_name = 'usuario/novo.html'
    success_url = reverse_lazy('inicio')

class UsuarioNewAPI(APIView):
    serializer_class = CadastroSerializer

    def post(self, validated_data):
        user = User.objects.create(
            username=self.request.POST.get('username', ''),
            email=self.request.POST.get('email', ''),
            first_name=self.request.POST.get('first_name', ''),
            last_name=self.request.POST.get('last_name', '')
        )

        user.set_password(self.request.POST.get('password', ''))
        user.save()
        
        return user




class LoginView(FormView):
    
    success_url = reverse_lazy('inicio')
    template_name = 'usuario/entrar.html'
    form_class = LoginUsuario        
    def post(self, request):
        username = self.request.POST.get('username', '')
        password = self.request.POST.get('password', '')            
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return(redirect('inicio'))
            else:
                print ("Sua conta foi desabilitada!")
        else:
            print ("Seu username e senha estavam incorretos.21111")

class infoPerfil(DetailView):
    queryset = User.objects.all()
    template_name = 'usuario/perfilInfo.html'
    def get_context_data(self, **kwargs):
        context = kwargs
        context['mangas'] = Manga.objects.filter(autor=context['object'].id)
        return context

class editarPerfil(UpdateView, LoginRequiredMixin):
    model = User
    form_class = perfilM
    template_name = 'usuario/perfilEdt.html'

    def get_success_url(self, **kwargs):
        print(self.request.user.id)
        if kwargs != None:
            return reverse_lazy('usuario:perfil', kwargs={'pk': self.request.user.id})
        else:
            return reverse_lazy('usuario:perfil', args=(self.request.user.id,))

    def get_form_kwargs(self):
        kwargs = super(editarPerfil, self).get_form_kwargs()
        if self.request.user == kwargs['instance']:
            kwargs.update(instance={
                'user': self.object,
                'perfil': self.object.perfil,
            })
            return kwargs
        else:
            raise PermissionDenied()


def sair(request):
    logout(request)
    return (redirect('/'))

usuario/templates/usuario/edtPerfil.html
{% extends 'inicio.html' %}
{% block content %}
{% if user.is_authenticated %}

<form action="" method="post" class="form-signin" enctype="multipart/form-data">
    {% csrf_token %}
    <input type='hidden' name='userID' value='{{user.id}}' />
    <input type='hidden' name='user' value='{{user.id}}' />
    <input type='hidden' name='perfilID' value='{{user.perfil.id}}' />
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-6 col-md-6">
                <div class="well well-sm">
                    <div class="row">
                        <div class="col-sm-6 col-md-4">
                            <img src="{{ user.perfil.capa.url }}" id="output" alt="" class="img-rounded img-responsive" />
                            <input type="file" name="capa" id="capa_id" onchange="loadFile(event)">
                            <script>
                                var loadFile = function(event) {
                                    var output = document.getElementById('output');
                                    output.src = URL.createObjectURL(event.target.files[0]);
                                };
                            </script>
                        </div>

                        <div class="col-sm-6 col-lg-12">
                            <label for="campo1">Nome:</label>
                            <input type="text" class="form-control" id="nome" name="nome" value="{{ user.first_name }}">
                        </div>
                        <div class="col-sm-6 col-lg-12">
                            <label for="campo1">Sobre Nome:</label>
                            <input type="text" class="form-control" id="Snome" name="Snome" value="{{ user.last_name }}">
                        </div>
                        <div class="col-sm-6 col-lg-12">
                            <label for="campo1">Email:</label>
                            <input type="email" class="form-control" id="email" name="email" value="{{user.email}}">
                        </div>
                        <div class="col-lg-6 col-lg-12">
                            <label for="campo1">Cidade:</label>
                            <input type="text" class="form-control" id="cdd" name="cdd" value="{{user.perfil.cidade}}">
                            <label for="campo1">Data de Nacimento:</label>
                            {{form.dn}}
                        </div>
                        <div class="col-sm-6 col-lg-12">
                            <label for="campo1">Sobre:</label>
                            <textarea name="sobre" id="sobre" cols="30" rows="10" class="form-control">
                                {{user.perfil.sobre}}
                            </textarea>

                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br>
    <div class="col align-items-lg-center">
            <input type="submit" class="btn btn-success" value="Salvar" />
            <a href="../../perfil/" class="btn btn-danger" role="button">Cancelar</a>    
    </div>    
    </form>
    {% else %}
     <li><a href="{% url 'usuario:entrar'%}?next={{request.path}}">Login</a></li>   
   {% endif %} 

{% endblock %}




<div class="row">
    <div class="col"></div>
    <div class="col">
    <center>
        <img src="{{ object.perfil.capa.url }}" name="aboutme" width="200" height="200" border="0" class="rounded-circle"></a>
        <div class="row">{{form.perfil.capa}}</div>
        <div class="row"><strong>Nome: </strong>{{form.user.first_name}}</div>
        <div class="row"><strong>Sobre Nome:</strong>{{form.user.last_name}}</div>
        <div class="row"><strong>Email:</strong>{{form.user.email}}</div>
    </center>
        <div class="row">
          <div class="col-5" style="left: -15px;"><strong>Data de Nacimento:</strong>{{form.perfil.dn}}</div>
          <div class="col-7" style="left: 15px;"><strong>Cidade</strong>{{form.perfil.cidade}}</div>
        </div>
    <center>
        <div class="row"><strong>Sobre:</strong>{{form.perfil.sobre}}</div>

    </center>
        
    
</div>
    <div class="col"></div>
</div>

usuario/templates/usuario/entrar.html
{% extends 'inicio.html' %}
{% block content %}
{% if user.is_authenticated %} 
<script>
    window.location = "/";
</script>
{% endif %}
<div class="row align-items-center justify-content-center">
    <form action="{% url 'usuario:entrar' %}" method="post" class="form-signin">
        {% csrf_token %}
        <label for="campo3">Usuario</label>
        {{form.username}}
        {{form.username.errors}}
        <label for="campo3">Senha</label>
        {{form.password}}
        {{form.password.errors}}
        <br>
        <button type="submit" class="btn btn-success ">Entrar</button>
    </form>
</div>
{% endblock %}

usuario/templates/usuario/listar.html
<html>

<head>
    <meta charset="UTF-8">
    <title>Lista de veículos cadastrados</title>
</head>

<body>
    <ul>
        {% for aux in object_list %}
        <li>
            {{ aux }}
        </li>
        {% endfor %}
    </ul>
</body>

</html>

usuario/templates/usuario/novo.html
{% extends 'inicio.html' %}
{% block content %}
{% if user.is_authenticated %} 
<script>
    window.location = "/";
</script>
{% endif %}
<div class="row align-items-center justify-content-center">
<form action="{% url 'usuario:cadastro' %}" method="post" class="form-signin">
    {% csrf_token %}
    <label for="campo1">Nome:</label>
    {{form.first_name}}
    {{form.first_name.errors}}
    <label for="campo2">Sobrenome</label>
    {{form.last_name}}
    {{form.last_name.errors}}
    <label for="campo3">Email</label>
    {{form.email}}
    {{form.email.errors}}
    <label for="campo3">Usuario</label>
    {{form.username}}
    {{form.username.errors}}
    <label for="campo3">Senha</label>
    {{form.password}}
    {{form.password.errors}}
    <label for="campo3">Confirmar Senha</label>
    {{form.password_confirm}}
    {{form.password_confirm.errors}}
    <br>
    <a href="/" class="btn btn-danger" role="button">Cancelar</a>    
    <button type="submit" class="btn btn-success">Salvar</button>
</form>
</div>
{% endblock %}

usuario/templates/usuario/perfil.html
{% extends 'inicio.html' %}
{% block content %}
<style>
    body{padding-top:30px;}

    .glyphicon {  margin-bottom: 10px;margin-right: 10px;}

    small {
    display: block;
    line-height: 1.428571429;
    color: #999;
    }
</style>
<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-6">
            <div class="well well-sm">
                <div class="row">
                    <div class="col-sm-6 col-md-4">
                        {% if user.perfil.capa == '' %} 
                        <img src="" alt="" class="img-rounded img-responsive" />
                        {% else %}
                        <img src="{{ user.perfil.capa.url }}" alt="" class="img-rounded img-responsive" />
                        {% endif %}
                    </div>
                    <div class="col-sm-6 col-md-8">
                        <h4>
                            {{ user.first_name }} {{ user.last_name }}</h4>
                        <p>
                            <i class="glyphicon glyphicon-envelope"></i>{{ user.perfil.cidade }}
                            <br />
                        <!--     <i class="glyphicon glyphicon-globe"></i><a href="http://www.jquery2dotnet.com">www.jquery2dotnet.com</a>-->
                            <br />
                            <i class="glyphicon glyphicon-gift"></i>{{user.perfil.dn}}</p>
                        <!-- Split button -->
                        <div class="btn-group">
                            <button type="button" class="btn btn-primary">
                                Social</button>
                            <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                                <span class="caret"></span><span class="sr-only">Social</span>
                            </button>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="#">Twitter</a></li>
                                <li><a href="https://plus.google.com/+Jquery2dotnet/posts">Google +</a></li>
                                <li><a href="https://www.facebook.com/jquery2dotnet">Facebook</a></li>
                                <li class="divider"></li>
                                <li><a href="#">Github</a></li>
                            </ul>
                        </div>
                        <p>
                            <a href="../editperfil/">Editar</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

___________________________________________________________________________________________________________
<br>Cont

<a href="{% url 'add:manga'  %}">Enviar</a>

    {% for aux in mangas %}
        {{aux.titulo}}<br>
    {% endfor %}
{% endblock %}

usuario/templates/usuario/perfilEdt.html
{% extends 'inicio.html' %}
{% block content %}
<form action="" method="post" class="form-signin" enctype="multipart/form-data">
    {% csrf_token %}
    <br>
    {% if exception %}
    <p>{{ exception }}</p>
    asdasdasdasd
  {% else %}
<input type='hidden' name='user' value='{{user.id}}'/>
      <div class="row">
          <div class="col"></div>
          <div class="col">
          <center>
              <img src="{{ object.perfil.capa.url }}" name="aboutme" id="output" width="200" height="200" border="0" class="rounded-circle">
              <div class="row">{{form.perfil.capa}}</div>
              <script>
                var loadFile = function (event) {
                    var output = document.getElementById('output');
                    output.src = URL.createObjectURL(event.target.files[0]);
                };
            </script>
              <div class="row"><strong>Nome: </strong>{{form.user.first_name}}</div>
              <div class="row"><strong>Sobre Nome:</strong>{{form.user.last_name}}</div>
              <div class="row"><strong>Email:</strong>{{form.user.email}}</div>
          </center>
              <div class="row">
                <div class="col-5" style="left: -15px;"><strong>Data de Nacimento:</strong>{{form.perfil.dn}}</div>
                <div class="col-7" style="left: 15px;"><strong>Cidade</strong>{{form.perfil.cidade}}</div>
              </div>
          <center>
              <div class="row"><strong>Sobre:</strong>{{form.perfil.sobre}}</div>
              <hr>
            <a href="/usuario/{{user.id}}" class="btn btn-danger" role="button">Cancelar</a>
            <button type="submit" class="btn btn-success">Salvar</button>

          </center>
              
          
      </div>
          <div class="col"></div>
      </div>
    {% endif %}
</form>
{% endblock %}

usuario/templates/usuario/perfilInfo.html
{% extends 'inicio.html' %}
{% block content %}
{% load static %}
    {% csrf_token %}
    <div class="row">
        <div class="col"></div>
        <div class="col">
        <center>
            <img src="{{ object.perfil.capa.url }}" name="aboutme" width="200" height="200" border="0" class="rounded-circle"></a>
            <h3 class="media-heading">{{object.first_name}} {{object.last_name}}</h3>
            <!--<span><strong>Skills: </strong></span>
                <span class="label label-warning">HTML5/CSS</span>
                <span class="label label-info">Adobe CS 5.5</span>
                <span class="label label-info">Microsoft Office</span>
                <span class="label label-success">Windows XP, Vista, 7</span>-->
                {% if user == object %} 
            <a href="editar/">Editar</a><br>
            {% endif %}
            <hr>
            <p class="text-left"><strong>Sobre: </strong><br>
                {{object.perfil.sobre}}
                </p>
        </center>
    </div>
        <div class="col"></div>
    </div>
    <hr>
    <center><h3>Meus mangas
    {% if user == object %} 
        <a href="{%url 'add:manga' %}"><small> Adicoinar</small></a>
    {% endif %}</h3></center>
    <div class="row" style="margin: 10px">
            
        {% for aux in mangas %}
            <div class="col-sm-6 col-md-4 col-lg-2 mt-2">
                    <div class="card card-inverse card-info">
                        <img class="card-img-top" src="{{aux.capa.url}}">
                        <div class="card-block">
                            <div class="card-title">
                                <a href="{%url 'add:manga' %}{{aux.id}}" >{{aux.titulo}}</a>
                                
                            </div>
                            <div class="card-text">
                                Tags: {{aux.tags}}<br>
                                 {% if user == object %}
                                    <a href="/add/manga/delete/{{aux.id}}/">Excluir</a>
                                 {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
        {% endfor %}
    </div>
{% endblock %}