projetoFinal/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from addConteudo.views import lista

urlpatterns = [
    path('', lista.as_view(), name='inicio'),
    path('usuario/', include('usuario.urls', namespace="usuario")),
    path('add/', include('addConteudo.urls', namespace="add")),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuario/urls.py
from django.urls import include, path
from django.conf import settings
from django.urls import re_path
from django.views.static import serve
from . import views
from rest_framework.authtoken import views as rest_framework_views


app_name = 'usuario'
urlpatterns = [
    path('novo/',   views.UsuarioNew.as_view(), name='cadastro'),
    path('novo/api/',   views.UsuarioNewAPI.as_view(), name='cadastro-api'),
    path('entrar/',   views.LoginView.as_view(), name='entrar'),
    path('entrar/api/',   views.entrarAPI.as_view(), name='entrar-api'),
    path('<int:pk>/', views.infoPerfil.as_view(), name='perfil'),
    path('<int:pk>/api', views.infoPerfil.as_view(), name='perfil-api'),
    path('<int:pk>/editar/',   views.editarPerfil.as_view(), name='editar-perfil'),
    path('api/',   views.teste.as_view(), name='api2'),
    path('api/<int:pk>/',   views.teste.as_view(), name='api'),
    path('sair/',   views.sair, name='sair'),
    
    #path('editar/<int:pk>/', views.VeiculosEdit.as_view(),
    #     name='editar-veiculo'),
    #path('excluir/<int:pk>/',  views.VeiculosDelete.as_view(),
    #     name='deletar-veiculo'),
]

templates/inicio.html
<!DOCTYPE html>
<html lang="pt">
    {% load static %}
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Projeto</title>
    <script src="{% static 'usuario/js/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'usuario/js/bootstrap/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'usuario/js/usuario.js' %}"></script>
    <script src="{% static 'usuario/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'usuario/js/jquery/jquery-ui.js' %}"></script>
    <!-- Bootstrap core CSS -->

    <link rel="stylesheet" id="bootstrap-css" type="text/css" href="{% static 'usuario/css/bootstrap/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'usuario/css/one-page-wonder.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'usuario/css/style.css' %}" />
    <!-- Custom fonts for this template -->
  
    <!-- Custom styles for this template -->

  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
      <div class="container">
        <a class="navbar-brand" href="/">Projeto</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %} 
            <a class="nav-link" href="/usuario/{{user.id}}/" >Ola, {{ user.first_name }}</a>
            <a class="nav-link" href="{% url 'usuario:sair' %}" >Sair</a>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'usuario:cadastro' %}" >Cadastrar</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'usuario:entrar' %}" >Entrar</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav><br><br><br>
  {% block content %}
  {% endblock %}


  
    <!-- Bootstrap core JavaScript row align-items-center justify-content-center-->
    
  </body>

</html>